 name: Update list.txt

on:
  workflow_dispatch:
    inputs:
      new_content:
        description: 'New content for list.txt'
        required: true
        default: ''
      commit_message:
        description: 'Commit message'
        required: true
        default: 'Update list.txt'

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update list.txt
      run: |
        echo "${{ github.event.inputs.new_content }}" > list.txt
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add list.txt
        git commit -m "${{ github.event.inputs.commit_message }}"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
